# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|
  config.vm.box_check_update = false
  config.vm.provision "shell", path: "basic_deploy.sh"

  # Kubernetes Master Node
  config.vm.define "master" do |master|
    master.vm.box = "ubuntu/bionic64"
    master.vm.hostname = "master.edu.lab"
    master.vm.network "public_network", ip: "SECOND_OPTION",  bridge: "my_adapter"
    master.vm.provider "virtualbox" do |vb|
      vb.name = "k8s-master"
      vb.memory = "1024"
      vb.cpus = "4"
      vb.customize ["modifyvm", :id, "--groups", "/k8s"]
    end
    master.vm.provision "shell", path: "init_master.sh"
  end

  NodeCount = 2

  # Kubernetes Worker Nodes
  (1..NodeCount).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.box = "ubuntu/bionic64"
      node.vm.hostname = "node-#{i}.edu.lab"
      node.vm.network "my_net_config", ip: "10.100.100.12#{i}",  bridge: "wlp3s0"
      node.vm.provider "virtualbox" do |vb|
        vb.name = "node-#{i}"
        vb.memory = "2048"
        vb.cpus = "4"
        vb.customize ["modifyvm", :id, "--groups", "/k8s"]
      end
      node.vm.provision "shell", path: "init_workers.sh"
    end
  end

end
